import defaultTheme from 'tailwindcss/defaultTheme';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.vue',
    ],
    safelist: [
        'w-[820px]',
        'w-72',
        '-left-36',
        'xl:-left-24',
        'grid-cols-12',
        'col-span-4',
        'col-span-5',
        'col-span-3',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                // Original colors
                "navy-base": "#070f1e",
                "navy-surface": "#0b1b33",
                "navy-card": "#102344",
                "primary-hover": "#9a3412",
                "accent-amber": "#b45309",
                "accent-coral": "#ef4444",
                "surface-low": "#eff4ff",
                brand: {
                    dark: '#070f1e',
                    navy: '#0b1b33',
                    surface: '#102344',
                    primary: '#c2410c',
                    amber: '#b45309',
                    coral: '#ef4444',
                },
                // New Material Design 3 Colors
                "on-secondary-container": "#53617d",
                "error": "#ba1a1a",
                "surface-container": "#e5eeff",
                "primary": "#a33900", // Overridden
                "outline": "#8e7166",
                "inverse-on-surface": "#eaf1ff",
                "on-tertiary-container": "#fffbff",
                "inverse-primary": "#ffb599",
                "on-primary-fixed": "#370e00",
                "primary-container": "#cc4900",
                "on-surface": "#0b1c30", // Overridden
                "surface-container-lowest": "#ffffff",
                "on-background": "#0b1c30",
                "primary-fixed": "#ffdbce",
                "on-tertiary-fixed": "#2a1700",
                "secondary-fixed-dim": "#b8c7e6",
                "outline-variant": "#e2bfb2",
                "on-primary-fixed-variant": "#7f2b00",
                "on-primary": "#ffffff",
                "surface-container-low": "#eff4ff",
                "surface-bright": "#f8f9ff",
                "on-surface-variant": "#5a4138", // Overridden
                "on-tertiary": "#ffffff",
                "tertiary-fixed-dim": "#ffb95f",
                "on-tertiary-fixed-variant": "#653e00",
                "on-error-container": "#93000a",
                "tertiary-fixed": "#ffddb8",
                "on-secondary-fixed": "#0c1c34",
                "surface-container-high": "#dce9ff",
                "surface": "#f8f9ff", // Overridden
                "surface-container-highest": "#d3e4fe",
                "on-secondary": "#ffffff",
                "secondary": "#505f7a",
                "tertiary": "#825100",
                "on-primary-container": "#fffbff",
                "background": "#f8f9ff",
                "primary-fixed-dim": "#ffb599",
                "surface-dim": "#cbdbf5",
                "surface-tint": "#a73a00",
                "on-secondary-fixed-variant": "#394761",
                "on-error": "#ffffff",
                "secondary-container": "#ceddfe",
                "inverse-surface": "#213145",
                "secondary-fixed": "#d6e3ff",
                "tertiary-container": "#a36700",
                "error-container": "#ffdad6",
                "surface-variant": "#d3e4fe"
            },
            fontFamily: {
                "headline": ["var(--font-primary)", "Mulish", "sans-serif"],
                "body": ["var(--font-primary)", "Mulish", "sans-serif"],
                "serif": ["Playfair Display", "serif"],
                "mono": ["var(--font-mono)", "monospace"],
                sans: ['var(--font-primary)', 'Mulish', ...defaultTheme.fontFamily.sans],
                // Material Design 3 Typography mapping to Mulish system
                "headline-lg": ["var(--font-primary)", "Mulish"],
                "body-md": ["var(--font-primary)", "Mulish"],
                "body-xl": ["var(--font-primary)", "Mulish"],
                "headline-sm": ["var(--font-primary)", "Mulish"],
                "display-hero-mobile": ["var(--font-primary)", "Mulish"],
                "display-hero": ["var(--font-primary)", "Mulish"],
                "headline-md": ["var(--font-primary)", "Mulish"],
                "headline-xl": ["var(--font-primary)", "Mulish"],
                "body-sm": ["var(--font-primary)", "Mulish"],
                "label-sm": ["var(--font-primary)", "Mulish"],
                "headline-accent": ["var(--font-primary)", "Mulish"],
                "label-md": ["var(--font-primary)", "Mulish"],
                "headline-xl-mobile": ["var(--font-primary)", "Mulish"],
                "body-lg": ["var(--font-primary)", "Mulish"]
            },
            fontSize: {
                "headline-lg": ["32px", {"lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "body-md": ["16px", {"lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400"}],
                "body-xl": ["18px", {"lineHeight": "28px", "letterSpacing": "-0.005em", "fontWeight": "400"}],
                "headline-sm": ["20px", {"lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                "display-hero-mobile": ["36px", {"lineHeight": "42px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "display-hero": ["56px", {"lineHeight": "64px", "letterSpacing": "-0.03em", "fontWeight": "800"}],
                "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "600"}],
                "headline-xl": ["44px", {"lineHeight": "50px", "letterSpacing": "-0.025em", "fontWeight": "700"}],
                "body-sm": ["14px", {"lineHeight": "20px", "letterSpacing": "0.005em", "fontWeight": "400"}],
                "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "600"}],
                "headline-accent": ["36px", {"lineHeight": "44px", "letterSpacing": "0.0em", "fontWeight": "400"}],
                "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
                "headline-xl-mobile": ["32px", {"lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "body-lg": ["18px", {"lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "400"}]
            },
            spacing: {
                "container-max": "80rem",
                "gutter-desktop": "2rem",
                "space-xl": "2rem",
                "space-4xl": "6rem",
                "space-2xs": "0.25rem",
                "space-3xl": "4.5rem",
                "space-xs": "0.5rem",
                "gutter-tablet": "1.5rem",
                "gutter-mobile": "1rem",
                "space-lg": "1.5rem",
                "space-md": "1rem",
                "space-sm": "0.75rem",
                "space-2xl": "3rem"
            },
            boxShadow: {
                'glow': '0 0 25px rgba(234, 88, 12, 0.35)',
                'glow-amber': '0 0 25px rgba(245, 158, 11, 0.35)',
                'glow-navy': '0 0 35px rgba(7, 15, 30, 0.4)',
                '2xs': '0 1px 2px rgba(0, 0, 0, 0.05)',
                'xs': '0 2px 4px rgba(0, 0, 0, 0.05)',
            },
        },
    },
    plugins: [
        require('@tailwindcss/typography'),
        require('@tailwindcss/forms'),
    ],
};