<?php

return [

    /*
    |--------------------------------------------------------------------------
    | AI Service Master Enable Toggle
    |--------------------------------------------------------------------------
    |
    | When disabled, the AI subsystem operates in fail-closed mode and
    | always routes requests to NoneChatAIProvider.
    |
    */

    'enabled' => (bool) env('CHAT_AI_ENABLED', false),

    /*
    |--------------------------------------------------------------------------
    | Default AI Provider
    |--------------------------------------------------------------------------
    |
    | Supported providers: "none", "fake" (test-only), "openai", "gemini".
    | Default is "none" (fail-closed, secure by default).
    |
    */

    'provider' => env('CHAT_AI_PROVIDER', 'none'),

    /*
    |--------------------------------------------------------------------------
    | Request & Network Timeouts
    |--------------------------------------------------------------------------
    |
    | Explicit timeout configuration to ensure external HTTP calls never hang.
    |
    */

    'timeout_seconds' => (int) env('CHAT_AI_TIMEOUT_SECONDS', 15),
    'connect_timeout_seconds' => (int) env('CHAT_AI_CONNECT_TIMEOUT_SECONDS', 5),

    /*
    |--------------------------------------------------------------------------
    | Context & Output Constraints
    |--------------------------------------------------------------------------
    |
    | Maximum input characters passed to the context builder and maximum
    | response tokens generated by the provider.
    |
    */

    'max_input_chars' => (int) env('CHAT_AI_MAX_INPUT_CHARS', 4000),
    'max_output_tokens' => (int) env('CHAT_AI_MAX_OUTPUT_TOKENS', 500),
    'temperature' => (float) env('CHAT_AI_TEMPERATURE', 0.7),

    /*
    |--------------------------------------------------------------------------
    | OpenAI Configuration
    |--------------------------------------------------------------------------
    */

    'openai' => [
        'api_key' => env('CHAT_AI_OPENAI_API_KEY', env('OPENAI_API_KEY')),
        'model' => env('CHAT_AI_OPENAI_MODEL', 'gpt-4o-mini'),
        'base_url' => env('CHAT_AI_OPENAI_BASE_URL', 'https://api.openai.com/v1'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Google Gemini Configuration
    |--------------------------------------------------------------------------
    */

    'gemini' => [
        'api_key' => env('CHAT_AI_GEMINI_API_KEY', env('GEMINI_API_KEY')),
        'model' => env('CHAT_AI_GEMINI_MODEL', 'gemini-1.5-flash'),
        'base_url' => env('CHAT_AI_GEMINI_BASE_URL', 'https://generativelanguage.googleapis.com/v1beta'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Human Handoff & AI Rate Limiting (CHAT-12)
    |--------------------------------------------------------------------------
    */

    'max_ai_replies_per_minute' => (int) env('CHAT_AI_MAX_REPLIES_PER_MINUTE', 5),

    'default_channel' => env('CHAT_AI_DEFAULT_CHANNEL', 'hybrid'), // 'ai' | 'hybrid' | 'human'

    'handoff_keywords' => [
        'gặp nhân viên',
        'tư vấn viên',
        'nhân viên hỗ trợ',
        'chăm sóc khách hàng',
        'gặp tư vấn viên',
        'người thật',
        'gặp người thật',
        'human',
        'agent',
    ],

    'handoff_notice' => 'Yêu cầu của bạn đã được chuyển tới chuyên viên tư vấn. Đội ngũ CSKH của Cửu Long sẽ hỗ trợ bạn ngay trong giây lát.',

    'fallback_notice' => 'Hệ thống AI hiện đang bận hoặc quá tải. Yêu cầu của bạn đã được chuyển tới nhân viên CSKH hỗ trợ trực tiếp.',

];
