name: Auto Deploy to cPanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Hosting via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/dev.truyenthongcuulong.com
            git fetch origin master
            git reset --hard origin/master
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
